### ISSUE TITLE
Add PACS storage to interface and pynetdicom client

### ISSUE THREAD

**Issue by dillonwilliams** [innolitics/pacsman#4]
Need ability to store:
 * PDF style reports
 * Annotations / regions of interest (maybe)
 * Arbitrary DICOM objects?

`pynetdicom` has a general DICOM `Dataset`, but the abstract methods can't be tied to a particular implementation. Probably better to have separate storage methods for each use-case, like `def send_report_to_pacs(self, patient_id, report_path)` , `def send_annotations_to_pacs(self, patient_id, instance_id, json_descriptor_list)`.

**Comment by johndgiese** [comment]
I think `pynetdicom` relies on `pydicom`'s `Dataset` class.  `pydicom`'s dataset is generic enough that I think we can use it in the API.

`pydicom`'s Datasets are like `numpy`'s `ndarray` class within numerical computing---most numerical programs use it as the common data structure.

@yujanshrestha what do you think about this?

**Comment by dillonwilliams** [comment]
`send_datasets` implements this.
